name: deploy mdbook
on:
  push:
    branches:
      - book
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Deploy github pages
        run: |
          mdbook build
          git worktree add gh-pages
          git config user.name "GH"
          git config user.email ""
          cd gh-pages
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../book/* .
          git add .
          git commit -m "deploy: $GITHUB_SHA"
          git push --force --set-upstream origin gh-pages
